### ISSUE TITLE
Installation of php-mode on Windows platform

### ISSUE THREAD

**Issue by doctorate** [ejmr/php-mode#228]
http://emacs.stackexchange.com/q/9669/2443

**Comment by syohex** [comment]
Would you tell us output of `M-: (executable-find "php")` ?
If you don't get correct path such as `c:\xampp\php.exe`, your PATH may be wrong.

**Comment by doctorate** [comment]
the output of evaluation was `nil`. The generic approach would be `M-x customize-group` then `php` then `php-executable` and when I enter the correct path: `c:\xampp\php.exe` this leads to `nil` after eval. So the question is how should I enter the path in the generic approach? the `php-mode` obviouslty doesn't respect the input in the generic approach.

**Comment by doctorate** [comment]
the output of evaluation was `nil`. The generic approach would be `M-x customize-group` then `php` then `php-executable` and when I enter the path in Windows: `c:\xampp\php.exe` this leads to `nil` after eval. So the question is how should I enter the path in the generic approach? As such, the `php-mode` obviously doesn't respect the input in the generic approach.

**Comment by syohex** [comment]
> how should I enter the path in the generic approach?

You should set `php-executable` as below. php-mode had issue about `php-executable`,
so I fixed the issue at #230. 

```lisp
(custom-set-variables
  '(php-executable "c:\xampp\php.exe"))
```

**Comment by doctorate** [comment]
Still not working. I changed the source as in issue. I used the generic approach to enter `c:\xampp\php.exe`, but when I close Emacs and open it again I find in the `init.el` file this line: ` '(php-executable "c:\\xampp\\php.exe")`. When I issue `C-c C-r` php.exe is not seen by emacs. When I issue `M-: (executable-find "php")` it returns nil too.

**Comment by syohex** [comment]
> I used the generic approach to enter c:\xampp\php.exe, but when I close Emacs and open it again I find this line introduced in the init.el file: '(php-executable "c:\\xampp\\php.exe")

Sorry I missed escape backslash.

**Comment by doctorate** [comment]
I am now lost. What should I enter into the `Php-Executable` parameter of the php group?

**Comment by doctorate** [comment]
Hmm, now I have `c:\xampp\php.exe`  in the `customize-group` php, whereas `c:\\xampp\\php.exe` in the `init.el` file, but by pressing `C-c C-r` for `php-send-region` cannot locate the executable file. `M-: (executable-find "php")` returns `nil`.

**Comment by doctorate** [comment]
Another related question: which executable php should work on Windows I have four executable files: `php.exe`, `php-cgi.exe`, `phpdbg.exe` and `php-win.exe`?

**Comment by ejmr** [comment]
> Another related question: which executable php should work on Windows I have four executable files...

For the purpose of Emacs I believe you want `php.exe`, e.g. for such things as `php-send-region`, although I must admit it's been some years since I've used such a setup on Windows, so I may be incorrect.

**Comment by syohex** [comment]
`php-send-region` works on my Windows machine by setting `php-executable` correctlly.

@doctorate  Don't worry about `M-: (executable-find "php") ` returns nil because `php-mode` always use
`php-executable` for using `php` command now.

**Comment by doctorate** [comment]
Now I entered the PATH environmental variables correctly like this `c:\xampp\php` instead of `c:\xampp\php\php.exe`, what happened is that by `M-: (executable-find "php")` I get this: `"c:/xampp/php/php.exe"` which is fine and `php-send-region` doesn't throw any error anymore, but what am I missing is the output of my code. @syohex can you please care to answer the post above on `SE` on how to setup `php-mode` on Windows machine with `XAMPP` installed? How would you normally get the result of your code in the browser. When do you send a region of code would that make the result pop up in your browser? Any help would be much appreciated. Thanks for the fix so far.

**Comment by syohex** [comment]
> how can I show the output from there in the browser?

Switch to `*PHP*` buffer and `M-x browse-url-of-buffer`(It may not work if you use latest firefox as
default browser, because emacs has bug in `browse-url` command for firefox)

**Comment by doctorate** [comment]
when I apply `C-c C-v` which is `browse-url-of-buffer` it does show the output in the browser (Chrome in my case) but it doesn't seem to see the linked `.css` file which happens to be in the same folder where my `.php` file is, am I missing something?

**Comment by syohex** [comment]
> but it doesn't seem to see the linked .css file which happens to be in the same folder where my .php file is, am I missing something?

No. `browse-url-of-buffer` supports only HTML itself, it cannot handle CSS or Javascript etc.
You should use [PHP builtin server](http://php.net/manual/en/features.commandline.webserver.php) and browser for such purpose. (Sorry, I don't know PHP well :-()

**Comment by ejmr** [comment]
@doctorate To add to what @syohex has already said, if you use `php-send-region` to execute some PHP and then open the results of the `*PHP*` buffer in a browser, you're probably never going to get the output you expect.  That is to say, it would not include any CSS or JavaScript you may have configured for your web-server, because that process by-passes the server entirely; the original intent of `php-send-region` was to run PHP code as if running a PHP script from the command-line, not something I think a lot of people do, but it was *barely* common enough in my own experience and use of PHP.  However, it sounds like what you want is to see the results of PHP as executed by your web-server; in that case, instead of using `php-send-region` you should instead browse to the PHP script through your local web-server, e.g. by browsing `http://localhost/foo/bar.php`.  That will execute the same PHP script but in the context of CGI, so you should then see any associated CSS and such.

**Comment by doctorate** [comment]
Thanks for this critical comment. I also realized what you have expounded. In this case I don't see much benefit of using this mode for my simple usage of php/css. The only thing that I can make use of from this mode so far is indentation but it is in my settings shadowed by other modes that intensely invested in `tab`.
